import ContextProviders from './context';
import { CssBaseline } from '@mui/material';
import './globals.css';

export const metadata = {
	title: 'Website Portfolio',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>
				<ContextProviders>
					<CssBaseline>{children}</CssBaseline>
				</ContextProviders>
			</body>
		</html>
	);
}
